# Generated by Django 3.0 on 2023-04-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_copydata_lettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adresses'},
        ),
    ]
