version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate

  quality:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py check
            flake8

  test:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pytest

  docker_image:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
            docker build -t $DOCKERHUB_USER/$DOCKERHUB_REPO:$CIRCLE_SHA1 .
            docker tag $DOCKERHUB_USER/$DOCKERHUB_REPO:$CIRCLE_SHA1 $DOCKERHUB_USER/$DOCKERHUB_REPO:latest
            docker push $DOCKERHUB_USER/$DOCKERHUB_REPO:$CIRCLE_SHA1
            docker push $DOCKERHUB_USER/$DOCKERHUB_REPO:latest

  deploy:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master:master

               

workflows:
  build-workflow:
    jobs:
      - build
      - quality
      - test
      - docker_image
      - deploy:
          filters:
            branches:
              only: master
