name: Badges

on:
  push:


jobs:
  update-badges:
    name: Update Badge on current branch
    runs-on: ubuntu-latest
    steps:
      - name: Display current branch
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})"
